name: mrd
channels:
  - ismrmrd
  - conda-forge
  - defaults
dependencies:
  - python=3.10.13
  # - ismrmrd::ismrmrd-python=1.14.0        # Package not available on Windows -- use pip install instead
  # - ismrmrd::siemens_to_ismrmrd=1.2.11    # Package not available on Windows
  - boost=1.76.0         # For ismrmrd
  - libxml2=2.9.12       # For ismrmrd
  - h5py=3.7.0           # For ismrmrd
  - matplotlib=3.8.2     # used by rgb.py and provides various visualization tools including colormaps
  - pydicom=2.4.3        # used by dicom2mrd.py to parse DICOM data
  - pynetdicom=2.0.2     # used by dicom2mrd.py to parse DICOM data
  - numpy=1.26.0
  - git=2.30.2
  - dos2unix=7.4.2       # For fixing line ending issues from Windows